version: 2.1
jobs:
  v2-5-5:
    docker:
      - image: circleci/ruby:2.5.5
        environment:
          BUNDLE_PATH: vendor/bundle

    steps: &steps
      - checkout

      - run:
          name: Which bundler?
          command: bundle -v

      - run:
          name: Bundle Install
          command: bundle install

      - run:
          name: Run rspec in parallel
          command: |
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out test_results/rspec.xml \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - store_test_results:
          path: test_results

  v2-6-5:
    docker:
      - image: circleci/ruby:2.6.5
        environment:
          BUNDLE_PATH: vendor/bundle

    steps: *steps

  latest:
    docker:
      - image: circleci/ruby:latest
        environment:
          BUNDLE_PATH: vendor/bundle

    steps: *steps

workflows:
  version: 2
  database-consistency:
    jobs:
      - v2-5-5
      - v2-6-5
      - latest
